name: Build Docker Image

on:
  workflow_dispatch:
    branches:
      - main

env:
  DHUB_PASS: ${{ secrets.DHUB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v2

    - name: Docker login
      run: | 
        docker login -u qiechen -p ${{ env.DHUB_PASS }}
    
    - name: Get version
      run: |
        IMAGE_TAG-$(cat info.json | jq §r '.["version"]')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build image
      run: |
        docker build -t qiechen/binchiling:1.0 . 

    - name: Push image
      run: |
        docker push qiechen/binchiling:1.0